/**
 * Pi Notify Extension
 *
 * Sends a native terminal notification when Pi agent is done and waiting for input.
 *
 * In tmux: uses a file-based approach. Each pi instance writes its state to
 * /tmp/pi-notify-{pane}.txt. A companion shell script (auto-installed to
 * ~/.config/tmux/pi-notify.sh) is triggered by tmux's status-interval and
 * fires OSC 777 directly to the outer terminal, bypassing tmux's pane
 * forwarding limitation for inactive panes.
 *
 * Outside tmux: writes OSC sequences directly to stdout.
 *
 * Supports:
 * - OSC 777: Ghostty, WezTerm, rxvt-unicode
 * - OSC 9: iTerm2
 * - OSC 99: Kitty
 * - Windows toast: Windows Terminal (WSL)
 * - Optional sound hook via PI_NOTIFY_SOUND_CMD
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { writeFileSync, unlinkSync, existsSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { homedir } from "node:os";

// ── File-based state (tmux) ──────────────────────────────────────

const STATUS_DIR = "/tmp";
const PREFIX = "pi-notify-";
const SCRIPT_PATH = `${homedir()}/.config/tmux/pi-notify.sh`;

function statusFile(): string | null {
  const pane = process.env.TMUX_PANE;
  return pane ? `${STATUS_DIR}/${PREFIX}${pane}.txt` : null;
}

function getTmuxWindow(): string {
  if (!process.env.TMUX_PANE) return "";
  try {
    const { execFileSync } = require("node:child_process");
    const context = execFileSync("tmux", [
      "display-message", "-p", "-t", process.env.TMUX_PANE,
      "[#I][#{window_name}]"
    ], { encoding: "utf8", timeout: 1000 }).trim();
    return context.replace(/[\x00-\x1F\x7F;]/g, " ");
  } catch {
    return "";
  }
}

function writeState(state: "working" | "ready", context = ""): void {
  const f = statusFile();
  if (!f) return;
  try { writeFileSync(f, `${state} ${process.pid} ${context}\n`); } catch { /* ok */ }
}

function removeStatus(): void {
  const f = statusFile();
  if (!f) return;
  try { if (existsSync(f)) unlinkSync(f); } catch { /* ok */ }
}

// ── Companion script (auto-installed for tmux) ───────────────────

const SCRIPT_CONTENT = `#!/usr/bin/env bash
# pi-notify.sh - auto-generated by pi-notify extension
# Polls state files and fires OSC 777 to the outer terminal when a pi
# instance transitions to "ready". Bypasses tmux pane forwarding by
# writing directly to the outer TTY.

set -euo pipefail

STATE_DIR="/tmp"
PREFIX="pi-notify-"
NOTIFIED_DIR="/tmp/pi-notify-notified"

mkdir -p "$NOTIFIED_DIR" 2>/dev/null || true

# Get the outer terminal TTY
TTY=$(tmux list-clients -F '#{client_tty}' 2>/dev/null | head -1 || true)
[[ -z "$TTY" || ! -w "$TTY" ]] && exit 0

for f in "$STATE_DIR"/"$PREFIX"*.txt; do
  [[ -f "$f" ]] || continue
  pane=$(basename "$f" .txt)
  pane="\${pane#"$PREFIX"}"

  read -r state pid context 2>/dev/null < "$f" || continue

  # Clean up stale files (process died)
  if [[ -n "$pid" && "$pid" != "0" ]] && ! kill -0 "$pid" 2>/dev/null; then
    rm -f "$f" "$NOTIFIED_DIR/$pane" 2>/dev/null || true
    continue
  fi

  if [[ "$state" == "ready" ]]; then
    if [[ ! -f "$NOTIFIED_DIR/$pane" ]]; then
      title="Pi"
      [[ -n "$context" ]] && title="$title $context"
      printf '\\033]777;notify;%s;Ready for input\\007' "$title" > "$TTY" 2>/dev/null || true
      touch "$NOTIFIED_DIR/$pane"
    fi
  elif [[ "$state" == "working" ]]; then
    rm -f "$NOTIFIED_DIR/$pane" 2>/dev/null || true
  fi
done
`;

function ensureScript(): void {
  try {
    mkdirSync(dirname(SCRIPT_PATH), { recursive: true });
    writeFileSync(SCRIPT_PATH, SCRIPT_CONTENT, { mode: 0o755 });
  } catch { /* ok */ }
}

// ── Direct OSC (non-tmux) ────────────────────────────────────────

function windowsToastScript(title: string, body: string): string {
  const type = "Windows.UI.Notifications";
  const mgr = `[${type}.ToastNotificationManager, ${type}, ContentType = WindowsRuntime]`;
  const template = `[${type}.ToastTemplateType]::ToastText01`;
  const toast = `[${type}.ToastNotification]::new($xml)`;
  return [
    `${mgr} > $null`,
    `$xml = [${type}.ToastNotificationManager]::GetTemplateContent(${template})`,
    `$xml.GetElementsByTagName('text')[0].AppendChild($xml.CreateTextNode('${body}')) > $null`,
    `[${type}.ToastNotificationManager]::CreateToastNotifier('${title}').Show(${toast})`,
  ].join("; ");
}

function wrapForTmux(sequence: string): string {
  if (!process.env.TMUX) return sequence;
  const escaped = sequence.split("\x1b").join("\x1b\x1b");
  return `\x1bPtmux;${escaped}\x1b\\`;
}

function notifyOSC777(title: string, body: string): void {
  process.stdout.write(wrapForTmux(`\x1b]777;notify;${title};${body}\x07`));
}

function notifyOSC9(message: string): void {
  process.stdout.write(wrapForTmux(`\x1b]9;${message}\x07`));
}

function notifyOSC99(title: string, body: string): void {
  process.stdout.write(wrapForTmux(`\x1b]99;i=1:d=0;${title}\x1b\\`));
  process.stdout.write(wrapForTmux(`\x1b]99;i=1:p=body;${body}\x1b\\`));
}

function notifyWindows(title: string, body: string): void {
  const { execFile } = require("node:child_process");
  execFile("powershell.exe", ["-NoProfile", "-Command", windowsToastScript(title, body)]);
}

function runSoundHook(): void {
  const command = process.env.PI_NOTIFY_SOUND_CMD?.trim();
  if (!command) return;
  try {
    const { spawn } = require("node:child_process");
    spawn(command, { shell: true, detached: true, stdio: "ignore" }).unref();
  } catch { /* ok */ }
}

function notifyDirect(title: string, body: string): void {
  const isIterm2 = process.env.TERM_PROGRAM === "iTerm.app" || Boolean(process.env.ITERM_SESSION_ID);
  if (process.env.WT_SESSION) {
    notifyWindows(title, body);
  } else if (process.env.KITTY_WINDOW_ID) {
    notifyOSC99(title, body);
  } else if (isIterm2) {
    notifyOSC9(`${title}: ${body}`);
  } else {
    notifyOSC777(title, body);
  }
  runSoundHook();
}

// ── Extension ────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  const inTmux = Boolean(process.env.TMUX);

  if (inTmux) {
    ensureScript();
  }

  pi.on("agent_start", async () => {
    if (inTmux) writeState("working");
  });

  pi.on("agent_end", async () => {
    if (inTmux) {
      writeState("ready", getTmuxWindow());
    } else {
      notifyDirect("Pi", "Ready for input");
    }
  });

  pi.on("session_shutdown", () => {
    if (inTmux) removeStatus();
  });

  process.on("exit", () => {
    if (inTmux) removeStatus();
  });
}
